### ISSUE TITLE
Ant project - SonarQube

### ISSUE THREAD

**Issue by kapitanyerik** [BME-MIT-IET/Meglepi-iet-2019#1]
1. @tmst96, @gwimil, @kapitanyerik  közösen utánanéz a SonarQube és az ant esetleges kompatibilitási problémáinak.
2. Amennyiben kompatibilisek, úgy a projektre beállítja a csapat a SonarQube-ot.

**Comment by gwimil** [comment]
Az ant és SonarQube között megoldható az egymással kompatibilis működés. 

https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+Ant 
Ezen a linken megtalálható a SonarQube Scanner for Ant, amely lehetővé tészi az Ant project scannelését. Az útmutató segítségével megoldható a projectfájl analizálása a SonarQube felületén.

Ha bármilyen nem várt mellékhatása lenne a SonarQube-nak az ant-tel, akkor
          https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner 
ezen a linken a SonarQube alapértelmezett scanner-jének letöltésével is megoldható a scannelés az útmutató szerint. 

Az se lenne baj ha külön mindkettő fajta scannelés be lenne üzemelve, hátha az egyik nem vesz hészre olyan bugot/codeSmellt/sebezhetőséget, amit a másik igen.

**Comment by gwimil** [comment]
Sikeresen beüzemeltem a SonarQube alapértelmezett scanner-jét a projekt analizálására.

**Comment by tmst96** [comment]
A SonarQube dokumentációja alapján módosítottam a build.xml tartalmát, a szükséges jar fájlt letöltöttem és a root mappába elhelyeztem. A SonarQube futtatása után már megtalálható a localhost:9000-es url-en a az analizált projekt.

**Comment by kapitanyerik** [comment]
A megoldást ellenőriztem, a pull requestet elfogadtam és a branch_t-t mergeltem a masterre.
