### ISSUE TITLE
Tesztek kódlefedettségének mérése és ez alapján tesztkészlet bővítése

### ISSUE THREAD

**Issue by borsy1397** [BME-MIT-IET/Meglepi-iet-2019#10]

**Comment by gwimil** [comment]
Amint megvannak az első JUnit tesztek, akkor elkezdem JaCoCo-val mérni a kódlefedettséget, majd az eredmény továbbítom.

**Comment by gwimil** [comment]
Jacoco-t hozzáadtam a pom file-hoz.

**Comment by kapitanyerik** [comment]
A jacoco működőképes a projekten, az issue-t lezárjuk.
