### ISSUE TITLE
Egységtesztek készítése/kiegészítése

### ISSUE THREAD

**Issue by borsy1397** [BME-MIT-IET/Meglepi-iet-2019#12]

**Comment by borsy1397** [comment]
Unit tesztek készítése szükséges az egyes osztályokhoz. A projekt felépítéséből adódóan ez nehezebben kivitelezhető, a kód nem átlátható az ömlesztettsége miatt. Javaslatom szerint az egyes osztályok kiszervezése külön fájlokba kiszervezése nagy többletmunkát igényelne, plusz a kód módosításával is járna, a láthatóságot kéne mindenképp megváltoztatni. 

Továbbá az egyes privát osztályok / privát metódusok elérése találtunk módszert ### (Java reflection), így eképpen eljárva igyekszünk teszteket megvalósítani

**Comment by borsy1397** [comment]
#15 done

**Comment by borsy1397** [comment]
RowNumberProvider tests added

**Comment by borsy1397** [comment]
RowValueProvider tests added.

A kód nem a legjobb, ugyanis nem vizsgál meg többféle eshetőséget (pl. helytelen paraméter)

**Comment by borsy1397** [comment]
UUIDProvider tests added

**Comment by borsy1397** [comment]
ValueProvider tests added

**Comment by gwimil** [comment]
ContantValueGenerator tests added

**Comment by tmst96** [comment]
BNodeGeneratorTest, TemplateURIGeneratorTest, TemplateLiteralGeneratorTest  tests added

**Comment by kapitanyerik** [comment]
A unit tesztek a csapat folyamatos review tevékenysége mellett kerültek hozzáadásra, a teszt lefedettség a jacoco visszajelzése alapján nagy, az issue-t lezárjuk.
