### ISSUE TITLE
Ant project - Travis

### ISSUE THREAD

**Issue by kapitanyerik** [BME-MIT-IET/Meglepi-iet-2019#2]
1. Faragó, Simon, Kapitány utánanéz az ant és a Travis kompatibilitási kérdésének.
2. Amennyiben kompatibilisek, akkor a csapat beállítja a projektre a Travis CI rendszert.

**Comment by tmst96** [comment]
A a root mappában a .travis.yml fájl létrehozása után a Travis megfelelően buildeli a projektet.

**Comment by kapitanyerik** [comment]
A következő elfogadott és merge-elt pull request-ben benne vannak a szükséges változtatások:
#6 
Az issuet lezárom, a probléma megoldva.
