### ISSUE TITLE
Maven project - ant -> maven-re való átírási kísérlete

### ISSUE THREAD

**Issue by kapitanyerik** [BME-MIT-IET/Meglepi-iet-2019#3]
@borsy1397  kísérletet tesz arra, hogy az alapvetően ant segítségével buildelhető projektet maven-el tudja buildelni a csapat. Nagy munka, nem biztos a siker, ezért párhuzamosan létezik az Ant és a Maven projekt.

**Comment by borsy1397** [comment]
A jelenleg használatban lévő Ant build rendszert terveztük átírni a modernebb Mavenre

**Comment by borsy1397** [comment]
A projektben használatos függősek verzióinak nem mindegyike található meg a central maven repositoryban, ezért a rendelkezésre álló .jar filok felhasználásával akartam létrehozni egy lokális maven repositoryt. Ez sikerült is, elkészült a megfelelő pom.xml, a projekt a Maven segítségével buildelődött lokálisan, viszont a Travis ellenőrzése során nem sikerült feloldani a függőségeket.

A feladat követelményeit enélkül is tudtuk teljesíteni, de a csapat igyekszek átállni Mavenre, így ez az Issue a feladat megoldásáig nem kerül lezárásra.

**Comment by borsy1397** [comment]
Utólag megoldódott a probléma, a lokálisan meglévő jar filok hiányoztak (egy félresikerült gitignore bejegyzés miatt), a felpusholásukat követően, illetve a pom.xml-ben történő javítás hatására a Travis megfelelőnek találta a kódot.

A projekt mavenre való átírása megtörtént, viszont a házi feladat első részének feladatai már elkészültek, így jelen pillanatban a csapat nem áll át maven buildre, csak a hátralevő részben, amennyiben szükséges. Így az issue továbbra is nyitva marad.

**Comment by borsy1397** [comment]
A házi feladat második részéből kifolyólag a csapat úgy döntött, hogy átállunk mavenre

**Comment by tmst96** [comment]
A maven-re átállás megtörtént, a maven branch merge-elve lett a master branch-csel.

**Comment by kapitanyerik** [comment]
A mostmár feleslegesnek számító, ant-hoz kapcsolódó fájlokat töröltük. A maven átállás sikerét a travis és a sonar is megerősítette.
